# Generated by Django 3.1 on 2020-08-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePageApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourses',
            name='coursecode',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
